### ISSUE TITLE
Yorum çekmek

### ISSUE THREAD

**Issue by MiPEK53** [evrenonur/trendyol-urun-veri-cekme#1]
[ratingScore] => stdClass Object
        (
            [averageRating] => 3.94
            [totalRatingCount] => 17
            [totalCommentCount] => 10
        )

Burada yorum sayısı vb. değerleri görebiliyoruz, 

peki yorumları ile birlikte ya da yorumları ayrı ayrı nasıl çekebiliriz.

**Comment by evrenonur** [comment]
Trendyol üzerinde browser ile atılan isteklere bakmanız lazım.
