### ISSUE TITLE
Kisitli urun

### ISSUE THREAD

**Issue by kendinibilmez13** [evrenonur/trendyol-urun-veri-cekme#2]
Oncelikle eline saglik, suanki kodu calistiridigimda sadece 23 adet urun bilgisini cekiyor, ama aslinda sayfada cok fazla urun var. sadece 23 adet urun cekmesinin sebebi nedir? Bunu istedigimiz kadar yapma imkani varmi? ornek olarak sadece 100 adet secmesini istesek veya tamaminin verisini istesek onu nasil yapariz?

Iyi gunler

**Comment by evrenonur** [comment]
Açık kaynak gelen veriye göre işlem yapabilirsin
